apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    app: helloworldapp
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworldapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldapp
  template:
    metadata:
      labels:
        app: helloworldapp
    spec:
      containers:
      - name: helloworldapp
        image: $dockerImage
        ports:
        - containerPort: 8000