kind: Service
apiVersion: v1
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    app: helloworldapp
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworldapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldapp
  template:
    metadata:
      labels:
        app: helloworldapp
    spec:
      containers:
      - name: helloworldapp
        image: $dockerImage
        ports:
        - containerPort: 80
